### ISSUE TITLE
Display public_day_entries

### ISSUE THREAD

**Issue by thelockymichael** [kurosh97/easyKeeper#5]
## Files
- [x] publicDiaryController
- [x] publicDiaryEntryRoute
- [x] publicDiaryEntryModel

## publicDiaryEntryModel Methods
 getPublicDiaryEntries
- [x] list all published user diary entries (must have title, date, author)

## Todo
When user clicks publish in My Diary page
- [x] takes current datetime and diary entry's dayEntryId and UserID
- [x] sends post request to publicDiaryEntryController (With current date time, selected DayEntryId and UserID)
- [x] saves publicDiaryEntry to public_day_entry table in mySQL databse
- [x] Home page displays public diary entries
- [x] Public diary entry list item must have the following -->
<ul>
<li>Title</li>
<li>Date</li>
<li>Author</li>
<li><strong>View button</strong></li>
</ul>
- [ ] When clicking view -->
Displays following data in modal (doesn't direct to another page. Stays on same home page)
<ul>
<li>Title</li>
<li>NoteText</li>
<li>DateTime</li>
<li>Mood</li>
<li>Username</li>
<li>Filename(<strong>DISPLAY IMAGE!</strong></li>
<li><strong>Cancel button</strong></li>
</ul>
